Repository Feeding-Thailand/thaifoodbank, pull requests merged in 2020-05, with the labels that each got.

#11 [hotfix] add checkAuth to post functions
  functions/post/index.js
Labels: bug

#8 add registerUser function
  .github/workflows/functest.yml
  functions/index.js
  functions/mapboxToken.js
  functions/package.json
  functions/post/createPost.js
  functions/post/index.js
  functions/posts/index.js
  functions/user/index.js
Labels: enhancement

#13 Finish createUser
  functions/index.js
  functions/mapboxToken.js
  functions/package.json
  functions/post/createPost.js
  functions/post/index.js
  functions/posts/index.js
  functions/user/index.js
Labels: enhancement

#14 firebase build fixed
  .cache/async-requires.js
  .cache/babelState.json
  .cache/redux/redux.node.state_0
  .cache/redux/redux.rest.state
  .cache/sync-requires.js
  gatsby-node.js
  src/components/constants.js
  src/components/helpList.js
  src/components/navHeader.js
  src/pages/help-matcher/index.js
  src/pages/help-matcher/register.js
  src/pages/index.js
Labels: bug

#15 implement latestPosts
  functions/posts/index.js
  functions/posts/latestPosts.js
Labels: enhancement

#17 Fixed image saving
  functions/.gitignore
  functions/mapboxToken.js
  functions/post/createPost.js
  functions/post/index.js
Labels: bug

#21 Add getPostById and photos images name data
  functions/post/createPost.js
  functions/post/getPost.js
  functions/post/index.js
Labels: enhancement

#24 Added requested data
  functions/post/getPost.js
  functions/posts/latestPosts.js
Labels: enhancement

#25 Added reCAPTCHA
  functions/.gitignore
  functions/checkRecaptcha.js
  functions/post/contactPost.js
  functions/post/index.js
  functions/posts/latestPosts.js
  functions/recaptchaSecret.js
Labels: enhancement

#29 Fixed latestPost and getPost routing conflict
  functions/post/getPost.js
  functions/post/index.js
  functions/post/latestPost.js
Labels: bug

#36 handle closePost
  functions/post/closePost.js
  functions/post/index.js
Labels: enhancement

#37 Minor features update
  functions/donate/donate.js
  functions/index.js
  functions/post/closePost.js
  functions/post/contactPost.js
  functions/post/createPost.js
  functions/post/deletePost.js
  functions/post/getPost.js
  functions/posts/geolocationPosts.js
  functions/posts/index.js
  functions/posts/latestPosts.js
  functions/user/index.js
  functions/user/settingsUser.js
Labels: enhancement

#38 deny multiple posts on same user
  functions/post/createPost.js
Labels: enhancement

#39 Deny duplicate pid
  functions/post/createPost.js
Labels: enhancement

#41 Maintain statistics
  functions/donate/donate.js
  functions/post/closePost.js
  functions/post/createPost.js
  functions/post/deletePost.js
Labels: enhancement

#43 Web interface
  gatsby-config.js
  package.json
  src/components/navHeader.js
  src/images/favicon.png
  src/pages/help-matcher/dashboard.js
  src/pages/help-matcher/index.js
  src/pages/help-matcher/register.js
  src/pages/help-matcher/view.js
  yarn.lock
Labels: enhancement

#44 Resolve latest functions
  functions/post/contactPost.js
  functions/post/index.js
Labels: enhancement

#47 Maintain donation as a subcollection
  .github/workflows/functionsCI.yml
  functions/.gitignore
  functions/donate/donate.js
  functions/package-lock.json
  functions/package.json
  functions/post/contactPost.js
  functions/post/createPost.js
  functions/post/deletePost.js
  functions/post/getPost.js
Labels: enhancement

#49 [fix] send data instead
  functions/post/getPost.js
Labels: bug

#51 Minor fixes
  functions/donate/donate.js
  functions/post/getPost.js
Labels: bug

#55 implement oldestPosts
  functions/posts/index.js
  functions/posts/oldestPosts.js
Labels: enhancement

#58 Added transactions collection
  functions/donate/donate.js
Labels: enhancement

#61 Web interface
  src/assets/css/app.css
  src/assets/css/theme.css
  src/assets/images/cool-background.svg
  src/assets/images/register-help.jpg
  src/assets/sass/app.scss
  src/assets/sass/theme.scss
  src/components/footer.js
  src/components/header.js
  src/components/helpList.js
  src/components/joinUs.js
  src/components/post-hero-md.js
  src/pages/help-matcher/index.js
  src/pages/help-matcher/register.js
  src/pages/help-matcher/view.js
  src/pages/index.js
  src/pages/privacy-policy.js
Labels: enhancement

#66 Fix authId on latestPost
  functions/post/latestPost.js
Labels: enhancement

#67 (almost) finalize functions
  functions/post/createPost.js
  functions/post/getPost.js
  functions/posts/oldestPosts.js
Labels: enhancement

#69 add pagination
  functions/posts/oldestPosts.js
Labels: enhancement

#70 Fix database query await and add reCAPTCHA on contactPost
  functions/post/index.js
  functions/posts/oldestPosts.js
Labels: enhancement

#72 Web interface update
  src/components/helpList.js
Labels: bug

#59 Add scheduler function
  functions/cleaner/index.js
  functions/doDelete.js
  functions/index.js
  functions/post/deletePost.js
Labels: enhancement

#81 Fix oldestPosts behavior
  functions/posts/oldestPosts.js
Labels: bug

#83 isDonated Added
  faker/index.js
  functions/post/index.js
  functions/post/isDonated.js
Labels: enhancement

#80 Deployed Pub/Sub Scheduler
  functions/cleaner/index.js
  functions/doDelete.js
  functions/index.js
  functions/post/deletePost.js
  functions/posts/oldestPosts.js
Labels: help wanted

#85 some bugs
  src/assets/css/app.css
  src/assets/sass/app.scss
  src/components/helpList.js
  src/components/personCard.js
  src/pages/about-us.js
  src/pages/help-matcher/index.js
  src/pages/help-matcher/map.js
  src/pages/help-matcher/register.js
  src/pages/help-matcher/view.js
Labels: enhancement

#88 add cancel donation
  functions/donate/cancel.js
  functions/donate/donate.js
  functions/donate/index.js
Labels: enhancement

#89 Add image resizing and converting to jpg function
  functions/helpers/formatImage.js
  functions/package-lock.json
  functions/package.json
  functions/post/createPost.js
Labels: enhancement

#91 Fixed same path
  functions/post/createPost.js
Labels: bug

#92 Update before refactor
  functions/donate/cancel.js
  functions/helpers/formatImage.js
  functions/package-lock.json
  functions/package.json
  functions/post/createPost.js
Labels: duplicate

#95 refactor project structure
  .github/workflows/CI.yml
  .github/workflows/functest.yml
  .github/workflows/functionsCI.yml
  .github/workflows/secretscan.yml
  functions/.gitignore
  functions/cleaner/index.js
  functions/doDelete.js
  functions/donate/cancel.js
  functions/donate/donate.js
  functions/donate/index.js
  functions/helpers/checkAuth.js
  functions/helpers/checkRecaptcha.js
  functions/helpers/doDelete.js
  functions/post/closePost.js
  functions/post/createPost.js
  functions/post/deletePost.js
  functions/post/index.js
  functions/post/isDonated.js
  functions/post/latestPost.js
  functions/posts/latestPosts.js
Labels: enhancement

#96 [fix] Promise.all wrong syntax
  functions/helpers/doDelete.js
  functions/post/createPost.js
Labels: bug

#97 Implemented directory deletion
  functions/helpers/doDelete.js
Labels: enhancement

#99 Finalize Functions
  .github/workflows/CI.yml
  .github/workflows/functest.yml
  .github/workflows/functionsCI.yml
  .github/workflows/secretscan.yml
  functions/.gitignore
  functions/cleaner/index.js
  functions/doDelete.js
  functions/donate/cancel.js
  functions/donate/donate.js
  functions/donate/index.js
  functions/helpers/checkAuth.js
  functions/helpers/checkRecaptcha.js
  functions/helpers/doDelete.js
  functions/post/closePost.js
  functions/post/createPost.js
  functions/post/deletePost.js
  functions/post/index.js
  functions/post/isDonated.js
  functions/post/latestPost.js
  functions/posts/latestPosts.js
Labels: duplicate, enhancement
